Addresssubmission
AfriGIS-South-Africa/afrigis-services-java pull request #19
Opened 2016-11-30 06:35 UTC by PieterCachet

Added Address Submission to AfriGIS Services.

2016-11-30 06:43 UTC, demaniak commented on addresssubmission/src/main/java/com/afrigis/services/addresssubmission/AddressSubmissionResponse.java
> +/*
@PieterCachet please remove this place holder text

2016-11-30 06:43 UTC, demaniak commented on addresssubmission/src/main/java/com/afrigis/services/addresssubmission/AddressSubmissionResponse.java
> +   String getClientID();
@PieterCachet add some javadocs please

2016-11-30 06:44 UTC, demaniak commented on addresssubmission/src/main/java/com/afrigis/services/addresssubmission/AddressSubmissionResult.java
> +    String getClientID();
@PieterCachet please add some javadoc

2016-11-30 06:44 UTC, demaniak commented on addresssubmission/src/main/java/com/afrigis/services/addresssubmission/AddressSubmissionResult.java
> +public interface AddressSubmissionResult {
What is the difference between this and `AddressSubmissionResponse`?

2016-11-30 07:49 UTC, PieterCachet commented on addresssubmission/src/main/java/com/afrigis/services/addresssubmission/AddressSubmissionResponse.java
> +/*
done

2016-11-30 07:49 UTC, PieterCachet commented on addresssubmission/src/main/java/com/afrigis/services/addresssubmission/AddressSubmissionResponse.java
> +   String getClientID();
done

2016-11-30 08:04 UTC, PieterCachet commented on addresssubmission/src/main/java/com/afrigis/services/addresssubmission/AddressSubmissionResult.java
> +public interface AddressSubmissionResult {
Opps, there is absolutely no difference. Was a happy type day. Will should be deleted
@demaniak all above done.

2016-11-30 09:22 UTC, demaniak commented on addresssubmission/src/test/java/com/afrigis/services/addresssubmission/AddressSubmissionTest.java
> +    protected static final String CLIENTID = "5B55B5B835";
Remove credentials.

Credentials have also been changed since now.

2016-11-30 09:25 UTC, demaniak commented on reversegeocode/pom.xml
> +	 <dependency>
Please just get formatting in line with the rest of the file?

2016-11-30 11:40 UTC, demaniak commented on addresssubmission/src/main/java/com/afrigis/services/addresssubmission/impl/AddressSubmissionResponseImpl.java
> +        final List<SubmissionResult> transform = new ArrayList<>();
Try this for me please:
```
return getResult() != null ? Arrays.asList (getResult()) : new ArrayList <>();
```

2016-11-30 11:41 UTC, demaniak commented on addresssubmission/src/main/java/com/afrigis/services/internal/saas/api2/dataCorrectionSubmit/package-info.java
> + * These classes manage all calls to Reverse Geocoding services.
Sure about that?

2016-11-30 11:42 UTC, demaniak commented on addresssubmission/src/main/java/com/afrigis/services/internal/saas/api2/dataCorrectionSubmit/params/AddressSubmissionParams.java
> + *
Add some javadoc.

2016-11-30 11:49 UTC, demaniak commented on addresssubmission/src/main/java/com/afrigis/services/internal/saas/api2/dataCorrectionSubmit/response/AddressSubmissionResponseSaasImpl.java
> +public class AddressSubmissionResponseSaasImpl extends AbstractResponse
This can be killed

2016-11-30 11:49 UTC, demaniak commented on addresssubmission/src/main/java/com/afrigis/services/internal/saas/api2/dataCorrectionSubmit/paresdObjects/ParsedAddressSubmissionData.java
> +public class ParsedAddressSubmissionData implements ParsedData {
Remove please

2016-11-30 11:50 UTC, demaniak commented on addresssubmission/src/main/java/com/afrigis/services/internal/saas/api2/dataCorrectionSubmit/paresdObjects/SubmissionResult.java
> +public class SubmissionResult {
Should also be removable.

2016-11-30 11:51 UTC, demaniak requested changes
Please see comments and adjust as necessary.

2016-11-30 11:53 UTC, demaniak commented on addresssubmission/src/test/java/com/afrigis/services/addresssubmission/AddressSubmissionTest.java
> +        assertTrue(addressSubmList.size() >= 1);
SLIGHTLY more elegant:
```
assertFalse (addressSubmList.isEmpty();
```

2016-11-30 12:03 UTC, PieterCachet commented on addresssubmission/src/main/java/com/afrigis/services/addresssubmission/impl/AddressSubmissionResponseImpl.java
> +        final List<SubmissionResult> transform = new ArrayList<>();
Done

2016-11-30 12:04 UTC, PieterCachet commented on addresssubmission/src/main/java/com/afrigis/services/internal/saas/api2/dataCorrectionSubmit/package-info.java
> + * These classes manage all calls to Reverse Geocoding services.
Done

2016-11-30 12:06 UTC, PieterCachet commented on addresssubmission/src/main/java/com/afrigis/services/internal/saas/api2/dataCorrectionSubmit/response/AddressSubmissionResponseSaasImpl.java
> +public class AddressSubmissionResponseSaasImpl extends AbstractResponse
Done

2016-11-30 12:06 UTC, PieterCachet commented on addresssubmission/src/main/java/com/afrigis/services/internal/saas/api2/dataCorrectionSubmit/paresdObjects/ParsedAddressSubmissionData.java
> +public class ParsedAddressSubmissionData implements ParsedData {
Done

2016-11-30 12:15 UTC, PieterCachet commented on addresssubmission/src/test/java/com/afrigis/services/addresssubmission/AddressSubmissionTest.java
> +        assertTrue(addressSubmList.size() >= 1);
Done

2016-11-30 12:15 UTC, PieterCachet commented on addresssubmission/src/test/java/com/afrigis/services/addresssubmission/AddressSubmissionTest.java
> +        assertTrue(addressSubmList.size() >= 1);
Done

2016-11-30 12:15 UTC, PieterCachet commented on addresssubmission/src/main/java/com/afrigis/services/internal/saas/api2/dataCorrectionSubmit/paresdObjects/SubmissionResult.java
> +public class SubmissionResult {
Still using this class.

2016-11-30 13:08 UTC, PieterCachet commented on addresssubmission/src/main/java/com/afrigis/services/internal/saas/api2/dataCorrectionSubmit/params/AddressSubmissionParams.java
> + *
Done

2016-11-30 13:08 UTC, PieterCachet commented
@demaniak Done changes above

2016-11-30 14:15 UTC, demaniak commented on addresssubmission/src/main/java/com/afrigis/services/internal/saas/api2/dataCorrectionSubmit/paresdObjects/SubmissionResult.java
> +public class SubmissionResult {
Sharp

2016-11-30 14:16 UTC, demaniak approved these changes
LGTM

2016-11-30 14:17 UTC, demaniak commented
@SydneyChadwick please double check me quickly?

2016-11-30 14:49 UTC, SydneyChadwick commented
Just one general thought... for each time the unit test runs, we're actually submitting the address for correction? Otherwise, LGTM.

2016-12-01 05:42 UTC, demaniak commented
@SydneyChadwick yes, we will, BUT at this time our CI setup is...foobar. So tests are ran manually.

2016-12-01 05:42 UTC, merged